name: SkyWarsCosta
author: djmichaelsaler
description: A Simple, fun, SkyWars plugin
version: 3.1
main: com.craftcostaserver.sw.HG
softdepend: [Multiverse-Core, MultiWorld, Vault, My Worlds]
commands:
  sw:
    description: SkyWarsCosta Base command